version: '2'

services:
  prestashop:
    image: ghcr.io/jakubk/presta_saved:latest
    ports:
      - 18125:80
      - 18126:443
    restart: always
    environment:
      PS_INSTALL_AUTO: 0
      PS_ERASE_DB: 0
      DB_SERVER: admin-mysql_db
      DB_USER: BE_180043
      DB_PASSWD: password
      DB_NAME: BE_180043
      PS_DEV_MODE: 0
      PS_DOMAIN: localhost:80
      PS_FOLDER_ADMIN: admin
      # example@example.com
      # P@ssw0rd
      # http://localhost/admin897rxfwwm
