version: '3.3'

services:
  prestashop:
    image: ghcr.io/jakubk/presta_saved:latest
    ports:
      - 18125:80
      - 18126:443
    restart: always
    networks:
      - admin-mysql_default
    environment:
      PS_INSTALL_AUTO: 0
      PS_ERASE_DB: 0
      DB_SERVER: actina15.maas
      #DB_SERVER: admin-mysql_db.1.ictj30t2zo86zdg2dprs0uvl0
      DB_USER: BE_180043
      DB_PASSWD: password
      DB_NAME: BE_180043
      PS_DEV_MODE: 0
      PS_DOMAIN: localhost:18125
      PS_DOMAIN_SSL: localhost:18126
      PS_FOLDER_ADMIN: admin
      # example@example.com
      # P@ssw0rd
      # http://localhost/admin897rxfwwm
networks:
  admin-mysql_default:
    external:
      name: admin-mysql_default