<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ccexd6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ccexd6/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2ccexd6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2ccexd6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2ccexd6\appProdProjectContainer([
    'container.build_hash' => '2ccexd6',
    'container.build_id' => '3b192a77',
    'container.build_time' => 1635370533,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ccexd6');
