<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHrgvln5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHrgvln5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHrgvln5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHrgvln5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHrgvln5\appProdProjectContainer([
    'container.build_hash' => 'Hrgvln5',
    'container.build_id' => '1d21b78e',
    'container.build_time' => 1635673642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHrgvln5');
