<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPbyoa74\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPbyoa74/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPbyoa74.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPbyoa74\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPbyoa74\appProdProjectContainer([
    'container.build_hash' => 'Pbyoa74',
    'container.build_id' => 'b81162a7',
    'container.build_time' => 1635098519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPbyoa74');
